spring: 
  thymeleaf: 
    cache: false
    mode: html
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    
  datasource: 
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: gkaigk1987
    driver-class-name: com.mysql.jdbc.Driver
    filter: stat
    maxActive: 100
    initialSize: 10
    minIdle: 1
 
  mail:
    host: smtp.ym.163.com
    username: gaok@youngerinfo.com
    password: *****
    default-encoding: UTF-8

mybatis: 
  mapper-locations: classpath:/gk/springboot/com/mapper/*.xml
  type-aliases-package: gk.springboot.com.model

server: 
  port: 8088
  
logging: 
  level: 
    gk.springboot.com: debug
    org.springframework: off
    